#!/bin/bash

echo "🚀 Setting up GitHub Actions for Vercel Deployment"
echo "=================================================="
echo ""
echo "Please follow these steps:"
echo ""
echo "Step 1: Create a Vercel Token"
echo "   Opening: https://vercel.com/account/tokens"
echo "   - Click 'Create Token'"
echo "   - Name: github-actions-finishi-waitlist"
echo "   - Scope: Finishi (finishi1)"
echo "   - Copy the token"
echo ""
read -p "Press Enter to open Vercel tokens page..." 
open "https://vercel.com/account/tokens" 2>/dev/null || xdg-open "https://vercel.com/account/tokens" 2>/dev/null
echo ""
echo "Step 2: Add GitHub Secrets"
echo "   Opening: https://github.com/finishi042/finishi-waitlist/settings/secrets/actions/new"
echo ""
echo "   Add these three secrets:"
echo ""
echo "   1. VERCEL_TOKEN (paste the token from Step 1)"
echo "   2. VERCEL_ORG_ID: team_MpB3XzzplgkRi1ilVKuGtbUi"
echo "   3. VERCEL_PROJECT_ID: prj_3IOe1eKAcMkGZ2uR8nZjxwa9cDAK"
echo ""
read -p "Press Enter to open GitHub secrets page..."
open "https://github.com/finishi042/finishi-waitlist/settings/secrets/actions/new" 2>/dev/null || xdg-open "https://github.com/finishi042/finishi-waitlist/settings/secrets/actions/new" 2>/dev/null
echo ""
echo "Step 3: Once secrets are added, push to deploy:"
echo "   git add -A"
echo "   git commit -m 'Add GitHub Actions deployment'"
echo "   git push"
echo ""
echo "✅ Setup complete! Check GitHub Actions tab after pushing."
